name: Create GitHub Release on NPM Publish

on:
  registry_package:
    types: [published]

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.registry_package.package_version.package_url == 'https://www.npmjs.com/package/mcp-code-graph'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.8.0

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: Release v${{ steps.package-version.outputs.version }}
          body: |
            ## Changes in v${{ steps.package-version.outputs.version }}
            
            This release was automatically created after publishing to NPM.
            
            ### Package Information
            - **Package**: mcp-code-graph
            - **Version**: ${{ steps.package-version.outputs.version }}
            - **NPM**: https://www.npmjs.com/package/mcp-code-graph
            
            For detailed changes, please check the commit history.
          draft: false
          prerelease: false